# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
loader_version=0.19.5
loom_version=1.17.20

# Mod Properties
version=1.0.0
group=com.thirsty

# Dependencies
fabric_api_version=0.92.12+1.20.1
cca_version=5.2.3
cloth_config=11.1.136
modmenu=7.2.2
create_version=6.0.7.0+mc1.20.1-build.1716
jei_version=15.62.0.217
emi_version=1.1.24+1.20.1
apple_skin=mc1.20.1-2.5.2